/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "Points",
      [
        {
          theme: 'Драки с бомжами',
          cloth: 'Царские одеяния',
          longitude: '37.628447',
          latitude: '55.757237',
          status: false,
          userId:  1,
          img: '/src/giphy%20(2).gif',
          clientId: null,
          agreed: false,
          reason: null,
          visibility: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          theme: 'Политический строй в Польше в 14 веке',
          cloth: 'Буду одет в класический костюмв красном шарфе. Буду на месте в 16:00 в маке',
          longitude: '37.65480310073764',
          latitude: '55.77638554757487',
          status: false,
          userId:  6,
          img: '/src/giphy%20(1).gif',
          clientId: null,
          agreed: false,
          reason: null,
          visibility: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          theme: 'ПАМАГИТЕ Я УПАЛ В ВОДУ!',
          cloth: 'В водолазном костюме, уже на месте',
          longitude: '37.70165824401853',
          latitude: '55.693352127643735',
          status: false,
          userId:  7,
          img: '/src/giphy%20(4).gif',
          clientId: null,
          agreed: false,
          reason: null,
          visibility: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          theme: 'Хочу выговориться, рассказать свою историю',
          cloth: 'Буду в зеленой толстовке с желтым рюкзаком. Гдето в 14:00 в МуМу.',
          longitude: '37.560917372589074',
          latitude: '55.67844785054861',
          status: false,
          userId:  8,
          img: '/src/giphy%20(5).gif',
          clientId: null,
          agreed: false,
          reason: null,
          visibility: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          theme: 'Пиво',
          cloth: 'Не одет',
          longitude: '37.61473321426388',
          latitude: '55.8589541089912',
          status: false,
          userId:  9,
          img: '/src/giphy%20(4).gif',
          clientId: null,
          agreed: false,
          reason: null,
          visibility: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          theme: 'Конфеты',
          cloth: 'Буду в час ночи',
          longitude: '37.8786411236572',
          latitude: '55.85725485766459',
          status: false,
          userId:  6,
          clientId: null,
          agreed: false,
          reason: null,
          visibility: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Points", null, {});
  },
};
